version: "3"

services:
  server:
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ec2-54-88-28-117.compute-1.amazonaws.com"
    
  reverse-proxy:
    image: traefik:v1.7
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock